# Do not inserts a blank line between shell prompts
add_newline = false

# Change the default prompt format
format = """\
$os\
$all$character"""

# Change the default prompt characters
[character]
success_symbol = "[=>](red)"
error_symbol = "[=>](red)"

# show current distro
[os]
format ='[$symbol](cyan)'   
disabled = false

[os.symbols]
Windows = " "
Arch = "󰣇 "
Ubuntu = " "
Macos = " "

# Shows the username
[username]
style_user = "green bold"
style_root = "red bold"
format = "\\[[$user]($style)\\] "
disabled = false
show_always = true

[directory]
truncation_length = 6
truncation_symbol = '…/'
home_symbol = " 󰠦 "
read_only_style = "red"
read_only = "  "
format = "\\[[$path]($style)\\][$read_only]($read_only_style) "

[git_branch]
symbol = "󰊢 "
format = "on [$symbol$branch]($style) "
truncation_length = 4
truncation_symbol = "…/"
style = "bold green"

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "🏳"
up_to_date = " "
untracked = " "
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = "󰏗 "
modified = " "
staged = '[++\($count\)](green)'
renamed = "󰖷 "
deleted = " "

[terraform]
format = "via [ terraform $version]($style) 壟 [$workspace]($style) "

[docker_context]
format = "via [ $context](bold blue) "

[helm]
format = "via [ $version](bold purple) "

[python]
symbol = "󰌠 "
python_binary = ['./venv/bin/python', 'python', 'python3']

[conda]
symbol = "󱔎 "
style = "green"

[nodejs]
format = "via [󰎙 $version](bold green) "

[kubernetes]
format = 'on [ $context\($namespace\)](bold purple) '
disabled = false
[kubernetes.context_aliases]
"clcreative-k8s-staging" = "cl-k8s-staging"
"clcreative-k8s-production" = "cl-k8s-prod"


